<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Team 9">

<title>Property Sales Price Prediction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="Summary_Paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="Summary_Paper_files/libs/quarto-html/quarto.js"></script>
<script src="Summary_Paper_files/libs/quarto-html/popper.min.js"></script>
<script src="Summary_Paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Summary_Paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="Summary_Paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Summary_Paper_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Summary_Paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Summary_Paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Summary_Paper_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Property Sales Price Prediction</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Team 9 </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="research-topic" class="level1">
<h1>Research Topic</h1>
<p>We are analyzing a selling record dataset from the New York City property market, which includes annual selling records of single buildings or unit buildings from 2016 to 2017. We are going to analyze the different factors present in our dataset to predict the sales price of the building in New York City. The aim of this project is to find relations and patterns of sales price w.r.t. various other factors to have a clear understanding of property price in NYC, and hopefully will help property companies or citizens that has interest in purchasing property at New York to have a prospect for the NY property price trend in the future.</p>
</section>
<section id="smart-questions" class="level1">
<h1>SMART Questions:</h1>
<ul>
<li>What type(s) of location variable(s) (Eg. block, borough, neighborhood) will affect the selling price most? (can answer by modeling)<br>
</li>
<li>How is the sale price of commercial property different from the sale price of residential property?<br>
</li>
<li>How is accuracy different if different machine learning models like linear regression, logistic regression, and random forest are applied?<br>
</li>
</ul>
</section>
<section id="importing-libraries" class="level1">
<h1>Importing Libraries</h1>
</section>
<section id="importing-data" class="level1">
<h1>Importing Data</h1>
<p>We imported the data about New York properties and checked its basic information</p>
<div class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>(84548, 22)
&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 84548 entries, 0 to 84547
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Unnamed: 0                      84548 non-null  int64 
 1   BOROUGH                         84548 non-null  int64 
 2   NEIGHBORHOOD                    84548 non-null  object
 3   BUILDING CLASS CATEGORY         84548 non-null  object
 4   TAX CLASS AT PRESENT            84548 non-null  object
 5   BLOCK                           84548 non-null  int64 
 6   LOT                             84548 non-null  int64 
 7   EASE-MENT                       84548 non-null  object
 8   BUILDING CLASS AT PRESENT       84548 non-null  object
 9   ADDRESS                         84548 non-null  object
 10  APARTMENT NUMBER                84548 non-null  object
 11  ZIP CODE                        84548 non-null  int64 
 12  RESIDENTIAL UNITS               84548 non-null  int64 
 13  COMMERCIAL UNITS                84548 non-null  int64 
 14  TOTAL UNITS                     84548 non-null  int64 
 15  LAND SQUARE FEET                84548 non-null  object
 16  GROSS SQUARE FEET               84548 non-null  object
 17  YEAR BUILT                      84548 non-null  int64 
 18  TAX CLASS AT TIME OF SALE       84548 non-null  int64 
 19  BUILDING CLASS AT TIME OF SALE  84548 non-null  object
 20  SALE PRICE                      84548 non-null  object
 21  SALE DATE                       84548 non-null  object
dtypes: int64(10), object(12)
memory usage: 14.2+ MB
None</code></pre>
</div>
</div>
<p>This dataset has 84,548 rows and 22 columns</p>
</section>
<section id="dataset-pre-processing" class="level1">
<h1>Dataset Pre-Processing</h1>
<p>Before we do the EDA and build models for this dataset, we need to clean the data first</p>
<section id="columns-manipulation" class="level2">
<h2 class="anchored" data-anchor-id="columns-manipulation">Columns Manipulation</h2>
<section id="changing-columns-name" class="level3">
<h3 class="anchored" data-anchor-id="changing-columns-name">Changing Column’s Name</h3>
<p>We changed the columns name into lower capital for better visualization and convenience.&nbsp;</p>
<div class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 84548 entries, 0 to 84547
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   unnamed                         84548 non-null  int64 
 1   borough                         84548 non-null  int64 
 2   neighborhood                    84548 non-null  object
 3   building_class_category         84548 non-null  object
 4   tax_class_at_present            84548 non-null  object
 5   block                           84548 non-null  int64 
 6   lot                             84548 non-null  int64 
 7   easement                        84548 non-null  object
 8   building_class_at_present       84548 non-null  object
 9   address                         84548 non-null  object
 10  apartment_number                84548 non-null  object
 11  zip_code                        84548 non-null  int64 
 12  residential_units               84548 non-null  int64 
 13  commercial_units                84548 non-null  int64 
 14  total_units                     84548 non-null  int64 
 15  land_square_feet                84548 non-null  object
 16  gross_square_feet               84548 non-null  object
 17  year_built                      84548 non-null  int64 
 18  tax_class_at_time_of_sale       84548 non-null  int64 
 19  building_class_at_time_of_sale  84548 non-null  object
 20  sale_price                      84548 non-null  object
 21  sale_date                       84548 non-null  object
dtypes: int64(10), object(12)
memory usage: 14.2+ MB</code></pre>
</div>
</div>
</section>
<section id="changing-columns-data-type" class="level3">
<h3 class="anchored" data-anchor-id="changing-columns-data-type">Changing column’s data type</h3>
<p>There are too many columns with inappropriate data type, so we need to convert them to the appropriate data type:</p>
<ol type="1">
<li>We converted land and gross square feet, property sales price, the number of residential, commercial and total units into continous variables<br>
</li>
<li>We converted variables that represent different locations like borough, neighborhood and zip code into categorical variable; we also converted variables represented different building categories, and different building tax categories into categorical variables<br>
</li>
</ol>
</section>
<section id="creating-some-new-features" class="level3">
<h3 class="anchored" data-anchor-id="creating-some-new-features">Creating Some New Features:</h3>
<p>We created a new column for percentage of residential units</p>
<div class="cell" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>1.000000    57072
0.000000     5021
0.666667      908
0.500000      560
0.750000      232
            ...  
0.991453        1
0.468750        1
0.986631        1
0.346154        1
0.940000        1
Name: percent_residential_units, Length: 180, dtype: int64</code></pre>
</div>
</div>
<p>We created another new column named ‘age’ by calculating the difference between the current year and the year it was built<br>
</p>
</section>
<section id="dropping-insignificant-columns" class="level3">
<h3 class="anchored" data-anchor-id="dropping-insignificant-columns">Dropping Insignificant Columns</h3>
<p>Based on the dataset information, we can see there’s an ambiguous column called ‘Unnamed’ that we don’t know what it’s used for, and another useless column ‘easement’ which has no value in its column for our analysis of sales price, so we decided to drop them first<br>
</p>
<p>Because we created a new feature called “age”, which is a better representation for the measure of a property’s history, so we can drop the column ‘year_built’</p>
<p>Lastly, we dropped some other columns too which had the same meaning as other columns.<br>
</p>
</section>
<section id="subsetting-out-inappropriate-values" class="level3">
<h3 class="anchored" data-anchor-id="subsetting-out-inappropriate-values">Subsetting Out Inappropriate Values</h3>
<p>Dropping duplicates<br>
</p>
<p>Removing data where commercial + residential doesn’t equal to total units</p>
<p>Removing rows with TOTAL UNITS == 0 and one outlier with 2261 units<br>
</p>
<p>Removing 0 square foot units<br>
</p>
</section>
</section>
<section id="dropping-null-values" class="level2">
<h2 class="anchored" data-anchor-id="dropping-null-values">Dropping Null Values</h2>
<p>After we finish the column manipulation, convert columns into appropriate data type, drop useless columns and create some new features, then we can drop the null or missing values in the whole dataset.<br>
</p>
<div class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 36420 entries, 0 to 84547
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype   
---  ------                          --------------  -----   
 0   borough                         36420 non-null  category
 1   neighborhood                    36420 non-null  category
 2   building_class_category         36420 non-null  category
 3   block                           36420 non-null  int64   
 4   lot                             36420 non-null  int64   
 5   address                         36420 non-null  object  
 6   zip_code                        36420 non-null  category
 7   residential_units               36420 non-null  int64   
 8   commercial_units                36420 non-null  int64   
 9   total_units                     36420 non-null  int64   
 10  land_square_feet                36420 non-null  float64 
 11  gross_square_feet               36420 non-null  float64 
 12  tax_class_at_time_of_sale       36420 non-null  category
 13  building_class_at_time_of_sale  36420 non-null  category
 14  sale_price                      36420 non-null  float64 
 15  sale_date                       36420 non-null  object  
 16  percent_residential_units       36420 non-null  float64 
 17  age                             36420 non-null  int64   
dtypes: category(6), float64(4), int64(6), object(2)
memory usage: 3.9+ MB</code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis-eda-visualization" class="level1">
<h1>Exploratory Data Analysis (EDA) &amp; Visualization</h1>
<section id="correlation-matrix" class="level2">
<h2 class="anchored" data-anchor-id="correlation-matrix">Correlation Matrix</h2>
<div class="cell" data-execution_count="15">
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19468\3853464610.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr = data_few_cols.corr()</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-16-output-2.png" width="698" height="585"></p>
</div>
</div>
<ul>
<li>According to the correlation matrix, we can see gross_square_feet have the strongest positive correlation with the sales price.<br>
</li>
</ul>
</section>
<section id="sales-prices-distribution" class="level2">
<h2 class="anchored" data-anchor-id="sales-prices-distribution">Sales Prices Distribution</h2>
<p>Only plotting values less than $10 million due to significant outliers (eg. 2.2 BILLION dollars)</p>
<div class="cell" data-execution_count="16">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-17-output-1.png" width="610" height="449"></p>
</div>
</div>
<ul>
<li>Most of the properties are selling below 0.2 millions dollar in New York from 2016 to 2017.<br>
</li>
</ul>
</section>
<section id="different-districts-selling-prices" class="level2">
<h2 class="anchored" data-anchor-id="different-districts-selling-prices">Different Districts Selling Prices</h2>
<div class="cell" data-execution_count="17">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-18-output-1.png" width="597" height="449"></p>
</div>
</div>
<ul>
<li>From the plot we can see that Manhattan property price is much higher than the other boroughs, so Manhattan is the most expensive district in New York.<br>
</li>
</ul>
</section>
<section id="violinplot-for-price-and-borough" class="level2">
<h2 class="anchored" data-anchor-id="violinplot-for-price-and-borough">Violinplot for price and borough</h2>
<div class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-19-output-1.png" width="600" height="449"></p>
</div>
</div>
<ul>
<li>From the violinplot, we can see that Manhattan is much skinnier as compared to others but it stretches to higher sales price.<br>
</li>
<li>Skinny plot represents that there is no specific price range in which Manhattan properties are getting sold.<br>
</li>
<li>Rest all the boroughs are fatter in lower sales price region.<br>
</li>
</ul>
</section>
<section id="plotting-square-footage-for-10k-and-those-not-equal-to-zero" class="level2">
<h2 class="anchored" data-anchor-id="plotting-square-footage-for-10k-and-those-not-equal-to-zero">Plotting Square Footage for &lt; 10k and those not equal to zero</h2>
<div class="cell" data-execution_count="19">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-20-output-1.png" width="601" height="449"></p>
</div>
</div>
<ul>
<li>The right skewed histogram indicating there are less values in upper end of the gross_square_feet.<br>
</li>
</ul>
</section>
<section id="square-footage-and-sale-price" class="level2">
<h2 class="anchored" data-anchor-id="square-footage-and-sale-price">Square Footage and Sale Price</h2>
<div class="cell" data-execution_count="20">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-21-output-1.png" width="470" height="476"></p>
</div>
</div>
<ul>
<li>The data points are very scattered are not aligning very well with the straight line.<br>
</li>
</ul>
</section>
<section id="age-and-sale-price" class="level2">
<h2 class="anchored" data-anchor-id="age-and-sale-price">Age and Sale Price</h2>
<div class="cell" data-execution_count="21">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-22-output-1.png" width="470" height="476"></p>
</div>
</div>
<ul>
<li>The data points are very scattered are not aligning very well with the straight line.<br>
</li>
</ul>
</section>
<section id="total-units-and-sale-price" class="level2">
<h2 class="anchored" data-anchor-id="total-units-and-sale-price">Total Units and Sale Price</h2>
<div class="cell" data-execution_count="22">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-23-output-1.png" width="470" height="470"></p>
</div>
</div>
<ul>
<li>We can see that there is a linear relation of total_units but it is not very clear as there are a lot of outliers.<br>
</li>
</ul>
</section>
<section id="selling-price-at-different-tax-classes" class="level2">
<h2 class="anchored" data-anchor-id="selling-price-at-different-tax-classes">Selling Price at Different Tax Classes</h2>
<div class="cell" data-execution_count="23">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-24-output-1.png" width="576" height="449"></p>
</div>
</div>
<ul>
<li>This plot gives valuable insights with respect to different tax classes. Properties with tax class 4 has the highest selling price.<br>
</li>
</ul>
</section>
<section id="distribution-of-percent-residential-units" class="level2">
<h2 class="anchored" data-anchor-id="distribution-of-percent-residential-units">Distribution of Percent Residential Units</h2>
<p>Not very informative but interesting as most buildings are 100% residential.<br>
</p>
<div class="cell" data-execution_count="24">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-25-output-1.png" width="610" height="449"></p>
</div>
</div>
</section>
</section>
<section id="model-building" class="level1">
<h1>Model Building</h1>
<p>We are going to build 4 models for predicting the sales_price of New York property, which are:<br>
</p>
<ul>
<li>Linear Regression<br>
</li>
<li>Decision Tree<br>
</li>
<li>Random Forest<br>
</li>
<li>K-NN<br>
The variables we are going to use are:<br>
borough, building_class_category, zip_codes, total_units, percent_residential_units, age, gross_square_feet, tax_class_at_time_of_sale, building_class_at_time_of_sale, and sale_price as the response variable.<br>
The variables we don’t use:<br>
We didn’t use Neighborhood, block, lot and address because they have the similar information as zip_codes and borough, and we think zip_codes and borough can provide better information on location.<br>
We didn’t use land_square_feet because we decided to use gross_sqaure_feet as a better variable for measuring the area.<br>
</li>
</ul>
<section id="removing-outliers" class="level2">
<h2 class="anchored" data-anchor-id="removing-outliers">Removing Outliers</h2>
<p>Because in the EDA Section, we’ve already seen our response variable sale_price is highly right skewed, so before we build the models, we have to remove the outliers or the model will be meaningless.<br>
We defined a function for detecting outliers, of which setting our outliers quantile below 25% and over 75%.<br>
</p>
<div class="cell" data-execution_count="25">
<div class="cell-output cell-output-stdout">
<pre><code>Number of outliers: 2743</code></pre>
</div>
</div>
<p>Define another function for removing outliers for dataframe.<br>
</p>
<div class="cell" data-execution_count="26">
<div class="cell-output cell-output-stdout">
<pre><code>Shape of our final cleaned dataframe is: (25744, 18)
&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 25744 entries, 222 to 84547
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype   
---  ------                          --------------  -----   
 0   borough                         25744 non-null  category
 1   neighborhood                    25744 non-null  category
 2   building_class_category         25744 non-null  category
 3   block                           25744 non-null  int64   
 4   lot                             25744 non-null  int64   
 5   address                         25744 non-null  object  
 6   zip_code                        25744 non-null  category
 7   residential_units               25744 non-null  int64   
 8   commercial_units                25744 non-null  int64   
 9   total_units                     25744 non-null  int64   
 10  land_square_feet                25744 non-null  float64 
 11  gross_square_feet               25744 non-null  float64 
 12  tax_class_at_time_of_sale       25744 non-null  category
 13  building_class_at_time_of_sale  25744 non-null  category
 14  sale_price                      25744 non-null  float64 
 15  sale_date                       25744 non-null  object  
 16  percent_residential_units       25744 non-null  float64 
 17  age                             25744 non-null  int64   
dtypes: category(6), float64(4), int64(6), object(2)
memory usage: 2.8+ MB
Basic info of our final cleand dataframe:
 None</code></pre>
</div>
</div>
<p>Check the distribution of the response again.<br>
</p>
<div class="cell" data-execution_count="27">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-28-output-1.png" width="602" height="449"></p>
</div>
</div>
<p>Much cleaner plot, although not exactly normal distribution but very close to normal distribution.<br>
</p>
</section>
<section id="traintest-split" class="level2">
<h2 class="anchored" data-anchor-id="traintest-split">Train/Test Split</h2>
<p>Before we starting to build the models, we need to split our cleaned dataframe into training set and testing set.<br>
Also we transformed categorical variables using onehotencoding and scaled the variables using fit_transform() function.<br>
</p>
<div class="cell" data-execution_count="28">
<div class="cell-output cell-output-stdout">
<pre><code>(29136, 351)
(7284, 351)
(29136,)
(7284,)</code></pre>
</div>
</div>
</section>
<section id="linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression">Linear Regression</h2>
<p>We build the linear regression with the regressors we mentioned above at first, then we got a fitting result with 48% R-Squared value, which is not a really bad score. However, we want to make sure this is a useful model (predicting useful results), so we also need to check the model assumptions.<br>
</p>
<ul>
<li><p><strong>Normally shaped response</strong>: Because we defined two functions to remove the outliers for our response variable sale_price in the Pre-processing section and checked its distribution on the EDA section, which is approximately normally distributed so we don’t have the problem of skewed response</p></li>
<li><p><strong>Multicollinearity</strong>: We checked the VIF values for our regressors, and we found zip_code and percentage_residential_units have extremly high VIF values (about 176 and 89 subsequently), which means we have a serious problem of multicollinearity and this can make our model prediction useless, so we removed these two regressors and checked the VIF values again and finally get every VIF values in an acceptable range (below 10)</p></li>
<li><p><strong>Linearity</strong>: We checked the scatter plot between the response variable sale_price and three continuous regressors in our model structure, which are total_units, Age, and gross_square_feet. We found a clear linear relationship between property’s sales price with total units and square footage, however, we can’t see a clear linear relation between property’s sales price and property’s age. Thus firstly we decided to romove regressor Age, but this can’t increase other evaluation values, instead, it dropped our R-Squared values about 2% down, so finally we decided to keep it After we finish these checkings we build our model again with the remaining regressors: age, total_units, gross_square_feet, borough, tax_class_at_time_of_sale, building_class_at_time_of_sale, and also added two more interaction terms.</p></li>
</ul>
<div class="cell" data-execution_count="29">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-30-output-1.png" width="600" height="449"></p>
</div>
</div>
<p>The residual plots for our final model looks acceptable.<br>
</p>
<div class="cell" data-execution_count="30">
<div class="cell-output cell-output-stdout">
<pre><code>R_squared value: 0.19761049879587889
adjusted R_squared value: 0.195360019886343</code></pre>
</div>
</div>
<p>The final linear model R-Squared value has dropped to 19.8%, which is definitely not acceptable for predicting a marketing continuous data like property sales price. Moreover, we can’t see the AIC and BIC change a lot compare with our previous model, which is also extremely high.<br>
Thus, finally we concluded that:<br>
</p>
<ul>
<li>Though we have some significant coefficients in our fitting summary, the response variable sale_price can be hardly explained with this model structure by using Linear Regression, and we will keep trying other types of models.&nbsp;</li>
</ul>
</section>
<section id="decision-tree" class="level2">
<h2 class="anchored" data-anchor-id="decision-tree">Decision Tree</h2>
<div class="cell" data-execution_count="31">
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-32-output-1.png" width="600" height="449"></p>
</div>
</div>
<ul>
<li>On checking R squared value for different depths of tree, accuracy fluctuated a lot and not giving a pattern. So no judgement can given by the decision tree regressor for our dataset.</li>
</ul>
</section>
<section id="random-forest" class="level2">
<h2 class="anchored" data-anchor-id="random-forest">Random Forest</h2>
<p>Random forest being a very strong modeling technique, gave better results than the previous models.<br>
We tried to run random forest using different permutations and combinations of hyperparameters.<br>
The best score model is as following<br>
</p>
<div class="cell" data-execution_count="32">
<div class="cell-output cell-output-stdout">
<pre><code>Training score: 0.6440346429343455
Testing score: 0.2890256072033246</code></pre>
</div>
</div>
<p>We got the score of around 29% which is not good enough for sales price prediction but it is better than the previous techniques.<br>
</p>
</section>
<section id="k-nearest-neighbor" class="level2">
<h2 class="anchored" data-anchor-id="k-nearest-neighbor">K-Nearest Neighbor</h2>
<p>As per professor’s feedback on our presentation, we tried K-Nearest Neighbor algorithm.<br>
Since, real estate brokers, agents, and people who want to buy a property knowingly or unknowingly follow K-NN approach to find the best property for them.<br>
So, using this approach for sales price prediction models makes a huge difference.<br>
</p>
<div class="cell" data-execution_count="34">
<div class="cell-output cell-output-display" data-execution_count="34">
<pre><code>Text(0, 0.5, 'score')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Summary_Paper_files/figure-html/cell-35-output-2.png" width="601" height="449"></p>
</div>
</div>
<ul>
<li>From the plot, R-squared score is negative initially and increasing with increasing K value at around 35% score, score values is getting saturated.<br>
</li>
<li>Best test score is achieved at K value of 23.<br>
</li>
</ul>
<div class="cell" data-execution_count="35">
<div class="cell-output cell-output-stdout">
<pre><code>Score at k = 23:  0.37172987602193475</code></pre>
</div>
</div>
<ul>
<li>We got the maximum score of around 37% at the k value of 23.</li>
</ul>
</section>
</section>
<section id="conclusion" class="level1">
<h1>CONCLUSION</h1>
<ul>
<li>Sales price was highly dependent on location type variables like boroughs.<br>
</li>
<li>Sales price was highly dependent on the gross_square_feet of the property.<br>
</li>
<li>Sales price was highly dependent on the tax class of the property.<br>
</li>
<li>Different models like linear regression, decision tree, random forest, and KNN gave different R squared score.<br>
</li>
<li>K-Nearest Neighbor performed best on our dataset with an score of 37%.<br>
</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>